name: code_generator
description: A package to help generate Dart code from existing code
version: 1.0.0

environment:
  sdk: ">=2.14.1 <3.0.0"

dev_dependencies:
  code_coverage: ^1.4.0
  lints: ^1.0.0
  mocktail: ^0.2.0
  test: ^1.20.1
dependencies:
  analyzer: ^4.0.0
  equatable: ^2.0.3
